# **CHAPTER 5**
# **Getting Started with pandas**

In [22]:
import pandas as pd
import numpy as np

In [2]:
from pandas import Series, DataFrame

## **5.1 Introduction to pandas Data Structures**

### **Series**

In [6]:
obj=pd.Series([4,7,-5,-3])

In [7]:
obj

0    4
1    7
2   -5
3   -3
dtype: int64

In [8]:
obj.values

array([ 4,  7, -5, -3])

In [9]:
obj.index #like range(4)

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj2=pd.Series([4,7,-5,3],index=['d','b','a','c'])

In [12]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [13]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [14]:
obj2['a']

-5

In [16]:
obj2['d']=6

In [18]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [19]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [20]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [23]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [24]:
'b' in obj2

True

In [25]:
'e' in obj2

False

In [26]:
sdata= {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [27]:
obj3=pd.Series(sdata)

In [28]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
states=['California', 'Ohio', 'Oregon', 'Texas']

In [30]:
obj4=pd.Series(sdata,index=states)

In [31]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [32]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [33]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [34]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [35]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [36]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [37]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [38]:
obj4.name='population'

In [39]:
obj4.index.name='state'

In [40]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [41]:
obj

0    4
1    7
2   -5
3   -3
dtype: int64

In [42]:
obj.index=['Bob','Steve','Jeff','Ryan']

In [43]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan    -3
dtype: int64

### **DataFrame**

In [44]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [45]:
frame=pd.DataFrame(data)

In [46]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [47]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [48]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [49]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],
                   index=['one','two','three','four','five','six'])

In [50]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [51]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [54]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [53]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [55]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [56]:
frame2['debt']=16.5

In [57]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [58]:
frame2['debt']=np.arange(6.)

In [59]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [61]:
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [62]:
frame2['debt']=val

In [63]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [64]:
frame2['eastern']=frame2.state=='Ohio'#state sütunun da Ohio olanları True döndürür

In [65]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [66]:
del frame2['eastern']

In [67]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [74]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [75]:
frame3=pd.DataFrame(pop)

In [76]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [77]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [78]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [80]:
pdata={'Ohio':frame3['Ohio'][:-1],
      'Nevada':frame3['Nevada'][:2]}

In [81]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [82]:
frame3.index.name='year';frame3.columns.name='state'

In [83]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [84]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [85]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### **Index Objects**

In [86]:
obj=pd.Series(range(3),index=['a','b','c'])

In [87]:
index=obj.index

In [88]:
index

Index(['a', 'b', 'c'], dtype='object')

In [89]:
index[1:]

Index(['b', 'c'], dtype='object')

In [91]:
index[1]='d'#TypeError

TypeError: Index does not support mutable operations

In [92]:
labels=pd.Index(np.arange(3))

In [93]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [94]:
obj2=pd.Series([1.5,-2.5,0],index=labels)

In [95]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [96]:
obj2.index is labels

True

In [97]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [98]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [99]:
'Ohio' in frame3.columns

True

In [100]:
2003 in frame3.columns

False

In [101]:
2003 in frame3.index

False

In [102]:
dup_labels=pd.Index(['foo','foo','bar','bar'])

In [103]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## **5.2 Essential Functionality**

### **Reindexing**

In [104]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [105]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [106]:
obj2=obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [107]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [108]:
obj3= pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [109]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [110]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [111]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),
                  index=['a','c','d'],
                  columns=['Ohio', 'Texas', 'California'])

In [112]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [113]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [115]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [127]:
states = ['Texas', 'Utah', 'California']

In [128]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [174]:
frame.loc[['a','b','c','d'],states]

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['b'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

### **Dropping Entries from an Axis**

In [133]:
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [134]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [135]:
new_obj=obj.drop('c')

In [136]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [137]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [138]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                 index=['Ohio','Colorado','Utah','New York'],
                 columns=['one','two','three','four'])

In [139]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [140]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [141]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [142]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [155]:
obj=pd.Series(np.arange(4.),index=['a','b','c','d'])

In [144]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [152]:
obj.drop('c',inplace=True)

In [153]:
obj

a    0.0
b    1.0
d    3.0
dtype: float64

### **Indexing, Selection, and Filtering**

In [145]:
obj['b']

1.0

In [146]:
obj[1]

1.0

In [147]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [149]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [150]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [151]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [156]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [157]:
obj['b':'c']=5

In [158]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [160]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                index=['Ohio','Colorado','Utah','New York'],
                 columns=['one','two','three','four' ])

In [161]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [162]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [163]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [164]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [165]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [166]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [168]:
data[data<5]=0

In [169]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### **Selection with loc and iloc**

In [170]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [175]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [176]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [177]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [171]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [172]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### **Integer Indexes**

In [26]:
ser=pd.Series(np.arange(3.))
ser
ser[-1]

KeyError: -1

In [27]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [29]:
ser2=pd.Series(np.arange(3.),index=['a','b','c'])
ser2[-1]

2.0

In [31]:
ser[:1]

0    0.0
dtype: float64

In [32]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [33]:
ser.iloc[:1]

0    0.0
dtype: float64

### **Arithmetic and Data Alignment**

In [34]:
s1=pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

In [35]:
s2=pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [37]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [38]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [39]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [41]:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),
                index=['Ohio', 'Texas', 'Colorado'])

In [42]:
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                                                       index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [43]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [44]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [45]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [46]:
df1=pd.DataFrame({'A':[1,2]})

In [47]:
df2=pd.DataFrame({'B':[3,4]})

In [48]:
df1

A
0  1
1  2

In [49]:
df2

B
0  3
1  4

In [50]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

#### **Arithmetic methods with fill values**

In [51]:
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),
                columns=list('abcd'))

In [52]:
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),
                columns=list('abcde'))

In [53]:
df2.loc[1,'b']=np.nan

In [54]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [55]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [56]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [57]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [58]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [59]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [60]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### **Operations between DataFrame and Series**

In [61]:
arr=np.arange(12.).reshape((3,4))

In [62]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [63]:
arr[0]

array([0., 1., 2., 3.])

In [64]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [65]:
frame=pd.DataFrame(np.arange(12.).reshape((4,3)),
                   columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [66]:
series=frame.iloc[0]

In [67]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [68]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [69]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [73]:
series2=pd.Series(range(3),index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [74]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [72]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [75]:
series3=frame['d']

In [76]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [77]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [78]:
frame.sub(series3,axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### **Function Application and Mapping**

In [79]:
frame=pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [80]:
frame

b         d         e
Utah    0.160558  0.365125 -2.322410
Ohio    0.694644  1.668203 -2.148311
Texas   1.144003  0.554913 -0.354420
Oregon  0.892858 -1.139878 -0.556518

In [81]:
np.abs(frame)

b         d         e
Utah    0.160558  0.365125  2.322410
Ohio    0.694644  1.668203  2.148311
Texas   1.144003  0.554913  0.354420
Oregon  0.892858  1.139878  0.556518

In [84]:
f=lambda x:x.max()-x.min()

In [85]:
frame.apply(f)

b    0.983445
d    2.808080
e    1.967990
dtype: float64

In [86]:
frame.apply(f,axis='columns')

Utah      2.687535
Ohio      3.816514
Texas     1.498424
Oregon    2.032736
dtype: float64

In [89]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

In [90]:
frame.apply(f)

b         d        e
min  0.160558 -1.139878 -2.32241
max  1.144003  1.668203 -0.35442

In [91]:
format=lambda x:'%.2f'% x

In [92]:
frame.applymap(format)

b      d      e
Utah    0.16   0.37  -2.32
Ohio    0.69   1.67  -2.15
Texas   1.14   0.55  -0.35
Oregon  0.89  -1.14  -0.56

In [93]:
frame['e'].map(format)

Utah      -2.32
Ohio      -2.15
Texas     -0.35
Oregon    -0.56
Name: e, dtype: object

### **Sorting and Ranking**

In [94]:
obj=pd.Series(range(4),index=['d', 'a', 'b', 'c'])

In [95]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [96]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),
                  index=['three', 'one'],
                   columns=['d', 'a', 'b', 'c'])

In [97]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [98]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [100]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [101]:
obj=pd.Series([4,7,-3,2])

In [102]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [103]:
obj=pd.Series([4,np.nan,7,np.nan,-3,2])

In [104]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [112]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [113]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [114]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [115]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [116]:
obj=pd.Series([7,-5,7,4,2,0,4])

In [117]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [118]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [119]:
## Assign tie values the maximum rank in the group
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [121]:
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],
                   'c':[-2,5,8,-2.5]})

In [122]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [123]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### **Axis Indexes with Duplicate Labels**

In [124]:
obj=pd.Series(range(5),index=['a','a','b','b','c'])

In [125]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [126]:
obj.index.is_unique

False

In [127]:
obj['a']

a    0
a    1
dtype: int64

In [128]:
obj['c']

4

In [129]:
df=pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])

In [130]:
df

0         1         2
a -0.227637 -0.899421 -0.844434
a -0.004336  0.455345 -0.762306
b  0.689340 -1.686198  0.810365
b -1.168751 -1.287358 -0.168528

In [131]:
df.loc['b']

0         1         2
b  0.689340 -1.686198  0.810365
b -1.168751 -1.287358 -0.168528

## **5.3 Summarizing and Computing Descriptive Statistics**

In [138]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],
                [np.nan,np.nan],[0.75,-1.3]],
               index=['a','b','c','d'],
               columns=['one','two'])

In [139]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [140]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [141]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [142]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [144]:
df.idxmax()

one    b
two    d
dtype: object

In [145]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [146]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [147]:
obj=pd.Series(['a','a','b','c']*4)

In [148]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### **Correlation and Covariance**

In [150]:
import pandas_datareader.data as web

In [151]:
all_data={ticker:web.get_data_yahoo(ticker)
         for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [152]:
price=pd.DataFrame({ticker:data['Adj Close']
                   for ticker,data in all_data.items()})

In [153]:
volume=pd.DataFrame({ticker:data['Volume']
                    for ticker, data in all_data.items()})

In [154]:
returns =price.pct_change()

In [155]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2020-11-23 -0.029743  0.026937 -0.001331 -0.004207
2020-11-24  0.011594  0.036056  0.017848  0.019610
2020-11-25  0.007467 -0.001768  0.000047  0.001442
2020-11-27  0.004826  0.001208  0.006359  0.012284
2020-11-30  0.021100 -0.006675 -0.005390 -0.018096

In [156]:
returns['MSFT'].corr(returns['IBM'])

0.5610002074107522

In [157]:
returns['MSFT'].cov(returns['IBM'])

0.00016015448137557305

In [158]:
returns.MSFT.corr(returns.IBM)

0.5610002074107522

In [159]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.475682  0.718476  0.657418
IBM   0.475682  1.000000  0.561000  0.522002
MSFT  0.718476  0.561000  1.000000  0.781195
GOOG  0.657418  0.522002  0.781195  1.000000

In [161]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000361  0.000147  0.000239  0.000208
IBM   0.000147  0.000265  0.000160  0.000141
MSFT  0.000239  0.000160  0.000308  0.000228
GOOG  0.000208  0.000141  0.000228  0.000277

In [162]:
returns.corrwith(returns.IBM)

AAPL    0.475682
IBM     1.000000
MSFT    0.561000
GOOG    0.522002
dtype: float64

In [163]:
returns.corrwith(volume)

AAPL   -0.095436
IBM    -0.075654
MSFT   -0.097511
GOOG   -0.164507
dtype: float64

### **Unique Values, Value Counts, and Membership**

In [1]:
import pandas as pd 
obj=pd.Series(['c','a','d','a','a','b','b','c','c'])

In [3]:
uniques=obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [4]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [5]:
pd.value_counts(obj.values,sort=False)

a    3
b    2
c    3
d    1
dtype: int64

In [6]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [8]:
mask=obj.isin(["b","c"])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [9]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [10]:
to_match=pd.Series(['c','a','b','b','c','a'])

In [13]:
unique_vals=pd.Series(["c","b","a"])

In [14]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [15]:
data=pd.DataFrame({'Qu1':[1,3,4,3,4],
                                        'Qu2':[2,3,1,2,3],
                                          'Qu3':[1,5,2,4,4] })

In [16]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [17]:
result=data.apply(pd.value_counts).fillna(0)

In [18]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0